# Generated by Django 5.1.15 on 2026-09-23 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_sitesetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('default', 'По умолчанию (сегодня или завтра)'), ('dates', 'Конкретные даты'), ('weekdays', 'Дни недели')], default='default', max_length=10, verbose_name='Режим')),
                ('dates', models.TextField(blank=True, default='[]', verbose_name='Даты уведомлений')),
                ('week_days', models.TextField(blank=True, default='[]', verbose_name='Дни недели уведомлений')),
                ('auditorium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.auditorium', verbose_name='Аудитория')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher', verbose_name='Преподаватель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на уведомления',
                'verbose_name_plural': 'Подписки на уведомления',
            },
        ),
    ]
