# Generated by Django 3.2.25 on 2024-04-02 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aud', models.IntegerField(verbose_name='Аудитория')),
                ('Corps', models.IntegerField(verbose_name='Корпус')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Of_Day', models.CharField(max_length=30, verbose_name='День недели')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Of_Group', models.CharField(max_length=50, verbose_name='Группа')),
                ('Form_Of_Education', models.CharField(max_length=50, verbose_name='Форма обучения')),
                ('Course', models.IntegerField(verbose_name='Курс')),
                ('Napravlenie', models.TextField(verbose_name='Направление')),
            ],
        ),
        migrations.CreateModel(
            name='Preps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Of_Preps', models.TextField(verbose_name='Фамилия И.О.')),
                ('Rank_Of_Preps', models.TextField(verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subj', models.TextField(verbose_name='Предмет')),
                ('Type_Of_Subj', models.TextField(verbose_name='Тип предмета')),
                ('Napravlenie', models.TextField(verbose_name='Направление')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_Of_Week', models.IntegerField(verbose_name='Номер недели')),
                ('Code_Of_Day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.day')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(max_length=50, verbose_name='Время')),
                ('Number_Of_Lesson', models.IntegerField(verbose_name='Номер занятия')),
                ('Code_Aud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aud')),
                ('Code_Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
                ('Code_Preps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.preps')),
                ('Code_Subj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='Code_Of_Lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson'),
        ),
    ]
