# Generated by Django 3.2.25 on 2024-05-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240402_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aud',
            options={'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'День', 'verbose_name_plural': 'Дни'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelOptions(
            name='preps',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'verbose_name': 'Неделя', 'verbose_name_plural': 'Недели'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='Day',
            field=models.CharField(default=1, max_length=20, verbose_name='День недели'),
            preserve_default=False,
        ),
    ]
