# Generated by Django 3.2.25 on 2024-05-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240507_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preps',
            name='Name_Of_Preps',
            field=models.TextField(blank=True, verbose_name='Фамилия И.О.'),
        ),
        migrations.AlterField(
            model_name='preps',
            name='Rank_Of_Preps',
            field=models.TextField(blank=True, verbose_name='Должность'),
        ),
    ]
