# Generated by Django 3.2.25 on 2024-05-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20240513_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aud',
            name='Aud',
            field=models.IntegerField(blank=True, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='aud',
            name='Corps',
            field=models.IntegerField(blank=True, verbose_name='Корпус'),
        ),
    ]
