# Generated by Django 3.2.25 on 2024-05-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20240513_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Course',
            field=models.IntegerField(blank=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='group',
            name='Form_Of_Education',
            field=models.CharField(blank=True, max_length=50, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='group',
            name='Name_Of_Group',
            field=models.CharField(blank=True, max_length=50, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='group',
            name='Napravlenie',
            field=models.TextField(blank=True, verbose_name='Направление'),
        ),
    ]
