# Generated by Django 3.2.25 on 2024-05-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20240513_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='Napravlenie',
            field=models.TextField(blank=True, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Subj',
            field=models.TextField(blank=True, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Type_Of_Subj',
            field=models.TextField(blank=True, verbose_name='Тип предмета'),
        ),
    ]
