# Generated by Django 3.2.25 on 2024-05-15 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20240513_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='Code_Of_Lesson',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='Day',
        ),
        migrations.RemoveField(
            model_name='week',
            name='Code_Of_Day',
        ),
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.day'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.week'),
            preserve_default=False,
        ),
    ]
