# Generated by Django 5.1.1 on 2024-10-22 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0008_auto_20240515_0857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
