# Generated by Django 5.1.1 on 2024-10-23 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0009_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.IntegerField(blank=True, verbose_name='Корпус')),
                ('number', models.IntegerField(verbose_name='Аудитория')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код')),
                ('title', models.TextField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Ученое звание')),
            ],
        ),
        migrations.RenameField(
            model_name='group',
            old_name='Course',
            new_name='old_course',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='Form_Of_Education',
            new_name='old_form_of_education',
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.IntegerField(default=0, verbose_name='Курс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='form_of_education',
            field=models.CharField(choices=[('о', 'Очная'), ('з', 'Заочная'), ('о-з', 'Очно-заочная')],
                                   default='не указана', max_length=50, verbose_name='Форма обучения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='format',
            field=models.CharField(blank=True, max_length=50, verbose_name='Формат проведения'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='number',
            field=models.IntegerField(
                choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'),
                         (7, 'Seventh'), (8, 'Eighth')], default=0, verbose_name='Номер занятия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='Code_Aud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_auditorium',
                                    to='main.aud'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='Code_Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_group',
                                    to='main.group'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='Code_Preps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_teacher',
                                    to='main.preps'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='auditorium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='main.auditorium'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='main.discipline'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.faculty'),
        ),
        migrations.AddField(
            model_name='group',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='main.faculty'),
        ),
        migrations.CreateModel(
            name='FullTimeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(
                    choices=[('пн', 'Понедельник'), ('вт', 'Вторник'), ('ср', 'Среда'), ('чт', 'Четверг'),
                             ('пт', 'Пятница'), ('сб', 'Суббота'), ('вс', 'Воскресенье')], max_length=2)),
                (
                'week_number', models.IntegerField(choices=[(1, 'First'), (2, 'Second')], verbose_name='Номер недели')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='PartTimeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='main.teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='main.teacher'),
        ),
    ]
