# Generated by Django 5.1.1 on 2024-10-23 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0010_auditorium_discipline_faculty_teacher_group_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='main.faculty'),
        ),
    ]
