# Generated by Django 5.1.1 on 2024-11-02 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0018_create_mixed_schedule'),
    ]

    operations = [
        migrations.RemoveField('Group', 'Name_Of_Group'),
        migrations.RemoveField('Group', 'old_form_of_education'),
        migrations.RemoveField('Group', 'old_course'),
        migrations.RemoveField('Group', 'Napravlenie'),

        migrations.RemoveField('Lesson', 'day'),
        migrations.RemoveField('Lesson', 'week'),
        migrations.RemoveField('Lesson', 'Time'),
        migrations.RemoveField('Lesson', 'Number_Of_Lesson'),
        migrations.RemoveField('Lesson', 'Code_Subj'),
        migrations.RemoveField('Lesson', 'Code_Group'),
        migrations.RemoveField('Lesson', 'Code_Preps'),
        migrations.RemoveField('Lesson', 'Code_Aud'),

        migrations.DeleteModel('Aud'),
        migrations.DeleteModel('Preps'),
        migrations.DeleteModel('Subject'),
        migrations.DeleteModel('Day'),
        migrations.DeleteModel('Week'),

    ]
