# Generated by Django 5.1.8 on 2025-08-30 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_drop_old_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='По специальному объявлению'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.discipline'),
        ),
    ]
