# Generated by Django 5.1.11 on 2026-06-29 07:35

from django.db import migrations


def copy_full_time_model_data(apps, schema_editor):
    FullTimeSchedule = apps.get_model('main', 'FullTimeSchedule')
    ConstantSchedule = apps.get_model('main', 'ConstantSchedule')

    old_instances = FullTimeSchedule.objects.all()
    new_instances = []

    for old_obj in old_instances:
        new_instances.append(
            ConstantSchedule(
                lesson=old_obj.lesson,
                week_day=old_obj.week_day,
                week_number=old_obj.week_number,
            )
        )

    if new_instances:
        ConstantSchedule.objects.bulk_create(new_instances)


def reverse_const_schedule_copy_data(apps, schema_editor):
    ConstantSchedule = apps.get_model('main', 'ConstantSchedule')
    ConstantSchedule.objects.all().delete()


def copy_part_time_model_data(apps, schema_editor):
    PartTimeSchedule = apps.get_model('main', 'PartTimeSchedule')
    MixedSchedule = apps.get_model('main', 'MixedSchedule')
    TemporarySchedule = apps.get_model('main', 'TemporarySchedule')

    old_instances = list(PartTimeSchedule.objects.all())
    old_instances.extend(list(MixedSchedule.objects.all()))
    new_instances = []

    for old_obj in old_instances:
        new_instances.append(
            TemporarySchedule(
                lesson=old_obj.lesson,
                date=old_obj.date,
            )
        )

    if new_instances:
        TemporarySchedule.objects.bulk_create(new_instances)


def reverse_temp_schedule_copy_data(apps, schema_editor):
    TemporarySchedule = apps.get_model('main', 'TemporarySchedule')
    TemporarySchedule.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0020_alter_lesson_discipline_constantschedule_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_full_time_model_data, reverse_code=reverse_const_schedule_copy_data),
        migrations.RunPython(copy_part_time_model_data, reverse_code=reverse_temp_schedule_copy_data)
    ]
