# Generated by Django 5.1.11 on 2026-07-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_lesson_is_special_alter_lesson_discipline'),
        ('main', '0021_auto_20260629_1235'),
    ]

    operations = [
    ]
