# Generated by Django 5.1.11 on 2026-07-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_merge_20260701_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.FloatField(choices=[(1, 'First'), (2, 'Second'), (2.5, 'Second And Half'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth')], verbose_name='Номер занятия'),
        ),
        migrations.DeleteModel(
            name='FullTimeSchedule',
        ),
    ]
