# Generated by Django 5.1.15 on 2026-09-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_lesson_number_delete_fulltimeschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parttimeschedule',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='MixedSchedule',
        ),
        migrations.DeleteModel(
            name='PartTimeSchedule',
        ),
    ]
