# Generated by Django 5.1.15 on 2026-09-10 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_parttimeschedule_lesson_delete_mixedschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDisciplineRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('show', 'Показывать дополнительно'), ('hide', 'Скрывать')], default='show', max_length=4, verbose_name='Режим')),
                ('apply_for_guests', models.BooleanField(default=False, verbose_name='Применять и для гостей')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.discipline', verbose_name='Дисциплина')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Правило отображения дисциплины',
                'verbose_name_plural': 'Правила отображения дисциплин',
                'unique_together': {('teacher', 'discipline', 'mode')},
            },
        ),
    ]
