# Generated by Django 5.1.15 on 2026-10-04 09:03

import datetime

from django.db import migrations, models
from django.utils import timezone


def backfill_updated_at(apps, schema_editor):
    """Истории дат по группам нет — всем группам проставляется текущая
    глобальная дата последнего изменения расписания из SiteSetting."""
    group = apps.get_model('main', 'Group')
    site_setting = apps.get_model('main', 'SiteSetting')

    value = site_setting.objects.filter(key='updated_at').values_list('value', flat=True).first()
    updated_at = None
    for fmt in ('%d.%m.%Y %H:%M', '%d.%m.%Y'):
        try:
            updated_at = timezone.make_aware(datetime.datetime.strptime(value, fmt))
            break
        except (TypeError, ValueError):
            continue
    if updated_at is None:
        updated_at = timezone.now()

    group.objects.all().update(updated_at=updated_at)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_notificationsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата последнего изменения расписания'),
        ),
        migrations.RunPython(backfill_updated_at, migrations.RunPython.noop),
    ]
